project:
  type: book

book:
  title: "Tutorial Bioinformatica"
  author: "Marcel Ferreira"
  date: "today"
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - sequenciamento.qmd
    - alinhamento.qmd
    - genotipagem.qmd
    - ONT.qmd
    - Dia5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-title: Nesta seção
  pdf:
    documentclass: scrreprt

editor: visual

