project:
  type: book

book:
  title: "Tutorial Bioinformatica"
  author: "Marcel Ferreira - Bolsista/CAPES"
  date: "today"
  downloads: [pdf]
  page-footer:
    left: |
      Este curso teve apoio CAPES-PROCAD Edital n° 16/2020
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - intro.qmd
    - primeiropassos.qmd
    - sequenciamento.qmd
    - alinhamento.qmd
    - genotipagem.qmd
    - ONT.qmd
    - Dia5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-title: Nesta seção
  pdf:
    documentclass: scrreprt

editor: visual

