---
engine: knitr
---

# Dia 2 - Alinhamento de sequências de DNA {.unnumbered}

## Arquivos

Os arquivos utilizados para estas analises serão os `.fastq` analisados no primeiro dia.

::: callout-warning
## Arquivos .fastq

Preste atenção para o caminho da pasta aonde estão os `.fastq`. Eles estão nas pastas **`Exome_ShortReads/fastq`** e `WGS_ShortReads/fastq`.
:::

## Atividades da manhã

<!-- -   Realize o alinhamento das amostras utilizando `BWA` e o genoma de referência `hg38.fa`; -->

<!-- -   Converta os arquivos `.sam` para o formato `.bam`; -->

<!-- -   Crie o indice dos arquivos `.bam`; -->

<!-- -   Alinhe novamente, desta vez utilizando `minimap2` e repita as demais etapas; -->

<!-- -   Utilize o `IGV` para visualizar os alinhamentos; -->

1.  **Indexação do Genoma de Referência:**

    -   Para o alinhamento de sequências utilizaremos o programa `bwa`. Há outros, como `bowtie2`, `minimap2`, que podem ser utilizados caso seja conveniente. Os comandos abaixo preparam o genoma de referência para o `bwa`.

    -   Antes de realizar o alinhamento, é necessário indexar o genoma de referência usando o comando **`bwa index`**. Isso cria arquivos que aceleram o processo de alinhamento.

        ```{bash,eval=FALSE}
        bwa index hg38.fa
        ```

    ::: callout-warning
    ## Indexação do genoma

    O processo para criar o indice do genoma via `bwa index` demora bastante tempo para ser realizado. Mesmo em máquimas com grandes capacidades de memória. Devido a isso colocamos na pasta **`Genome/index`** os arquivo resultantes desta etapa, que são os arquivos com extensão `.amb`, `.ann`, `.bwt`, `.fai`, `.pac` e `.sa`.

    O genoma de referência humano esta no arquivo `hg38.fa`. Esse é a última versão do genoma de referência e a mais utilizada no mundo.
    :::

2.  **Alinhamento de Sequências:**

    -   Use o **`bwa mem`** para alinhar suas sequências de DNA ao genoma de referência.

        ```{bash,eval=FALSE}
        bwa mem -R "@RG\tID:{SAMPLE}\tSM:{SAMPLE}" hg38.fa {SAMPLE}_r1.fastq {SAMPLE}_r2.fastq -o {SAMPLE}.sam
        ```

    Substitua `{SAMPLE}` pelos nomes dos arquivos correspondentes.

    ::: callout-tip
    ## Automatizando o processo (Opicional)

    Caso tenha experiência em programação, você pode utilizar um `loop`, como `for` ou `while`, para rodar todas as amostras ao mesmo tempo. Você pode utilizar o própio `bash` (ubuntu) ou sua linguagem de programação favorita, como `python`, `perl`, `R`, etc.

    Você poderá incluir as etapas seguintes no mesmo `loop`.
    :::

3.  **Converter Formato SAM para BAM e ordenar os reads:**

    -   O arquivo de saída do **`bwa mem`** é no formato SAM. Converta-o para o formato BAM, mais compacto e eficiente.

        ```{bash,eval=FALSE}
        samtools sort {SAMPLE}.sam > {SAMPLE}.bam
        ```

4.  **Indexar o Arquivo BAM:**

    -   Ordene o arquivo BAM para facilitar a busca e indexe-o para melhorar o desempenho de ferramentas subsequentes.

        ```{bash,eval=FALSE}
        samtools index {SAMPLE}.bam
        ```

<!-- 5.  **Remoção de Duplicatas (opcional):** -->

<!--     -   Dependendo da aplicação, você pode querer remover duplicatas do seu arquivo BAM para evitar viés em análises subsequentes. -->

<!--     -   `samtools rmdup alinhamento_sorted.bam alinhamento_nodups.bam` -->

5.  **Visualização do Alinhamento:**

    -   Use o `IGV` (Integrative Genomics Viewer) para visualizar o alinhamento (`{SAMPLE}.bam`) e verificar sua qualidade.

        ::: callout-important
        ## Regiões com reads

        Os arquivos `fastq` fornecidos para este curso foram preparados contendo apenas as regiões que estão nos arquivos `bed` fornecidos na pasta `Genome/`.
        :::

<!-- 6.  **Avaliação de Cobertura:** -->

<!--     -   Utilize o comando **`samtools depth`** para calcular a cobertura do genoma e avaliar a profundidade de sequenciamento em diferentes regiões. -->

<!--     -   `samtools depth alinhamento_sorted.bam > cobertura.txt` -->

6.  **Use o `IGV` para observar várias amostras ao mesmo tempo**

## Atividades da tarde

Para resolver os exercícios, utilizem todas as amostras do conjunto de dados, com exceção da amostra HG00097.

1.  Qual a cobertura das amostras para os marcadores `PentaE`, `PentaD`, `vWA` **`[PODEM SER OUTROS]`**.
2.  Qual é a profundidade média de cobertura das leituras alinhadas?
3.  Há alguma região com uma alta porcentagem de *mismatches* ou *indels* no genes MC1R e SLC45A2?
4.  Quão uniformemente as leituras estão distribuídas no genoma de referência?
