---
engine: knitr
---

# ANEXO: Dicas para uso do Ubuntu/WSL {.unnumbered}

## Navegação e Diretórios

### Listar Conteúdo do Diretório

```{bash, eval=F}
ls
```

### **Mudar de Diretório**

```{bash, eval=F}
cd nome_do_diretorio
```

### **Diretório Atual**

```{bash,eval=F}
pwd
```

### **Criar Diretório**

```{bash,eval=F}
mkdir nome_do_novo_diretorio
```

## **Manipulação de Arquivos**

### **Copiar Arquivo**

```{bash,eval=F}
cp arquivo_origem destino
```

### **Mover/Renomear Arquivo**

```{bash,eval = F}
mv arquivo_origem novo_nome_ou_destino
```

### **Remover Arquivo**

```{bash,eval=F}
rm nome_do_arquivo
```

## **Visualização de Conteúdo**

### **Visualizar Conteúdo do Arquivo**

```{bash,eval = F}
cat nome_do_arquivo
```

### **Visualizar Conteúdo do Arquivo (página por página)**

```{bash,eval=F}
less nome_do_arquivo
```

## **Pacotes e Atualizações**

### **Atualizar Lista de Pacotes**

```{bash,eval=F}
sudo apt update
```

### **Atualizar Pacotes Instalados**

```{bash,eval=F}
sudo apt upgrade
```

### **Instalar Novo Pacote**

```{bash,eval=F}
sudo apt install nome_do_pacote
```

## **Gerenciamento de Usuários**

### **Adicionar Usuário ao Grupo**

```{bash,eval=F}
sudo usermod -aG nome_do_grupo nome_do_usuario
```

### **Mudar Senha do Usuário**

```{bash,eval=F}
passwd nome_do_usuario
```

## **Processos**

### **Listar Processos**

```{bash,eval=F}
ps aux
```

### **Matar um Processo por ID**

```{bash,eval=F}
kill -9 processo_id
```

### **Monitorar Recursos do Sistema (htop)**

```{bash,eval=F}
htop
```

### **Medir Tempo de Execução de um Comando (time)**

```{bash,eval=F}
time comando_a_ser_medido
```

## **Rede**

### **Verificar Configurações de Rede**

```{bash,eval=F}
ifconfig
```

### **Testar Conexão com um Endereço IP**

```{bash,eval=F}
ping endereco_ip
```

## **Entrada e Saída Padrão (stdin/stdout)**

-   **stdin (Standard Input):** É a entrada padrão de dados. Um programa pode ler dados a partir do stdin. Exemplo:

    ```{bash,eval=F}
    cat < nome_do_arquivo
    ```

-   **stdout (Standard Output):** É a saída padrão de dados. Um programa geralmente imprime resultados no stdout. Exemplo:

    ```{bash,eval=F}
    ls > lista_de_arquivos.txt
    ```

-   **stderr (Standard Error):** É a saída padrão para mensagens de erro. Exemplo:

    ```{bash,eval=F}
    comando_inexistente 2> erro.log
    ```

## **Outros Comandos Úteis**

### **Ajuda sobre um Comando**

```{bash,eval=F}
man nome_do_comando
```

### **Sair do Terminal**

```{bash,eval=F}
exit
```
