---
engine: knitr
---

# Dia 4 - Análise de sequenciamento Oxford Nanopore {.unnumbered}

::: callout-important
## Importante

O software `guppy` só esta disponível para download via comunidade da Oxford Nanopore. Para este tutorial fornecemos um arquivo `.tar` para instalação em sua máquina. O arquivo esta na pasta **WorkshopDados/guppy_installer/**

Para instalar siga os seguintes passos:

Acesse a pasta que contem o arquivo `.tar` e descompacte;

```{bash,eval=F}
tar -xf ont-guppy-cpu_6.5.7_linux64.tar.gz
```

Verifique o caminho completo para a pasta

```{bash,eval=F}
pwd
```

Executando `guppy` via caminho completo (Exemplo pedindo ajuda)

```{bash,eval=F}
./guppy_basecaller --help
```
:::

## Atividades da manhã

1.  **Realize uma chamada de base utilizando guppy (Opicional):**

    -   Verifique os workflows disponíveis para esta versão de `guppy`;

        ```{bash,eval=F}
        ./Downloads/ont-guppy-cpu/bin/guppy_basecaller --print_workflows
        ```

    -   Sabendo que este sequenciamento foi realizado utilizando o kit SQK-LSK108 e a flowcell MIN106, qual a configuração a ser utilizada?

    -   Realize a chamada de base para todos os arquivos `fast5` contidos na pasta **WorkshopDados/fast5/**;

        ```{bash,eval=F}
        ./Downloads/ont-guppy-cpu/bin/guppy_basecaller –i [PASTAFAST5] –s /

        ./guppy_out –c [CONFIG].cfg  --num_callers 2 --cpu_threads_per_caller 1
        ```

    ::: callout-warning
    ## Aviso

    O tempo de execução da chama de base (para este conjunto de dados) é superior a **12 horas** em máquinas de uso pessoal, e pode acabar inutilizando seu uso. Caso deseje praticar, recomendamos que seja feito em um momento onde não precise da máquina para outras atividades. Para este tutorial utilize o resultado da chamada de base contido na pasta **WorkshopDados/LongReadsFastq/**
    :::

2.  **Avaliação da qualidade do arquivo resultado `.fastq`:**

    -   Utilize o `NanoPlot` para gerar gráficos de qualidade da amostra;

        ```{bash,eval=F}
        NanoPlot --fastq [AMOSTRA].fastq -o [OUTDIR] --N50 --verbose
        ```

3.  **Filtre as leituras baseado no tamanho e qualidade:**

    -   Utilize `chopper` para isso.

        ```{bash,eval=F}
        chopper < [AMOSTRA].fastq -q [QUALIDADE] -l [TAMANHO_MIN] > [AMOSTRA]_filtrada.fastq
        ```

    ::: {.callout-important collapse="true"}
    ## Por que usar `<` no comando `chopper`?

    O comando `<` garante que o arquivo fastq da amostra seja direcionado para entrada (**`stdin`**) do comando no `chopper`. Em nossas experiências já tivemos a necessidade de utilizar algumas vezes e outras não.
    :::

4.  **Alinhamento das Sequências:**

    -   Use o `minimap2` para alinhar suas sequências de DNA ao genoma de referência.

        ```{bash,eval=F}
        minimap2 -ax map-ont [REFERENCE_GENOME].fa [AMOSTRA].fastq /

        -R "@RG\tID:{SAMPLE}\tSM:{SAMPLE}" -t [THREADS] > [AMOSTRA].sam
        ```

    ::: callout-caution
    ## Consumo de memória durante a etapa

    O alinhamento via `minimap2` tem pico de consumo de memória de \~ 13 GB.
    :::

    -   Realize novamento utilizando `bwa mem` desta vez (Opicional);

    ::: callout-warning
    ## Tempo de execução do `bwa`

    Atenção, o `bwa` demora quase 10x mais que o `minimap2`
    :::

    ```{bash,eval=F}
    bwa mem -x ont2d [REFERENCE_GENOME].fa [AMOSTRA].fastq /

    -R "@RG\tID:{SAMPLE}\tSM:{SAMPLE}" -t [THREADS] > [AMOSTRA].sam
    ```

5.  **Gerar o arquivo BAM indexado:**

    -   Repita os passos 3 e 4 do dia 2 utilizando `samtools`;

6.  **Visualização do Alinhamento:**

    -   Importe o `BAM` para o `IGV` e avalie sua qualidade;
    -   Compare as amostras com suas respectivas amostras de short reads;

7.  **Realize a Genotipagem das Amostras de long reads:**

    -   Utilize o `freebayes` para realizar a genotipagem e modo similar ao passo 3 do dia 3;

    ::: callout-warning
    ## Tempo de execução da genotipagem em Long Reads

    O tempo de execução do `freebayes` para arquivos de ONT pode ser bem demorado! Você pode optar por modificar o arquivo `bed` fornecido para trabalhar com menos regiões.

    Para os formulários utilize o `vcf` resultante em **WorkshopDados/pre_run/Dia4/**
    :::

    -   Repita as métricas de filtragem utilizadas no passo 4 do dia 3;
    -   Repita os passos 5 e 6 do dia 3, comparando aos resultados de short reads.

8.  **Análise de modificações de bases**

    -   Use modkit para avaliar as modificações de base.

        ```{bash, eval=FALSE}
        modkit pileup {sample}.bam {sample}_pileup.bed --log-filepath {sample}.log
        --ref path/to/reference.fasta
        --preset traditional
        ```

    -   Avalie as modificações no IGV.

## Atividades da tarde

1.  Avalie a qualidade das leituras das amostras com `NanoPlot`. Qual a qualidade média das sequencias?
2.  Quais o intervaldo de tamanhos das leituras de cada amostra?
3.  Compare a genotipagem dos genes MC1R e SLC45A2 obtidas com ONT com as obtidas com short reads.
4.  s
5.  Avalie as modificações 5mC e 5hmC na região promotora dos genes MC1R e SLC45A2.
