---
engine: knitr
---

# Dia 1 - Sequenciamento de DNA {.unnumbered}

::: callout-important
## Importante

Verifique se o `FASTQC` esta instalado.
:::

## Arquivos

Serão utilizados os arquivos contidos na pasta **`WorkshopDados/shortReads/`**.

Estão dados vieram do projeto 1000 genomas (<https://www.internationalgenome.org/home>) e compreendem 10 amostras: dois trios e quatro amostras isoladas.

## Atividades

O controle de qualidade (QC) dos dados é uma etapa crítica na análise de sequenciamento de nova geração (NGS) para garantir a confiabilidade dos resultados. Abaixo estão as etapas típicas do controle de qualidade:

1.  **Análise Inicial com FASTQC:**
    -   Execute o `FASTQC` nas suas leituras brutas para avaliar a qualidade geral. Isso inclui gráficos e estatísticas que indicam a distribuição da qualidade das bases ao longo das reads, a presença de adaptadores, a presença de sequências *overrepresented*, entre outros.
2.  **Identificação de Adaptadores e Trimagem:**
    -   Com base nos resultados do `FASTQC`, identifique a presença de adaptadores e sequências indesejadas nas extremidades das reads. Utilize o `Trimmomatic` para remover essas sequências, garantindo que apenas dados de alta qualidade sejam mantidos.

        ::: callout-important
        ## `Trimmomatic` - Instalação e uso

        O `Trimmomatic` é um software escrito em java que deve ser executado utilizando o comando `java -jar CAMINHO/.jar`.

        Como sugestão recomendamos que deixe este arquivo na pasta Downlodas em sua `home`. Lembre-se se alterar `USER` para o seu nome de usuário. Desde modo os comandos a seguir serão executados sem erros.
        :::

    -   Adapte o comando abaixo para a amostra que esta analisando, substituindo HG00099 pelo código dela:

        ```{bash, eval=FALSE}
        java -jar '/home/USER/Downloads/Trimmomatic-0.39/trimmomatic-0.39.jar' PE -phred33 ShortReadsFastq/HG00099_r1.fastq ShortReadsFastq/HG00099_r2.fastq trimmed_r1.fastq trimmed_r1_unpaired.fastq trimmed_r2.fastq trimmed_r2_unpaired.fastq ILLUMINACLIP:'/home/USER/Downloads/Trimmomatic-0.39/adapters/TruSeq3-PE.fa':2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
        ```
3.  **Remoção de Leituras de Baixa Qualidade:**
    -   Algumas leituras podem conter regiões de baixa qualidade. Considere a remoção dessas leituras ou a trimagem de regiões específicas usando ferramentas adequadas, dependendo da natureza do problema. Utilize o comando a baixo para manter leituras com qualidade acima de 27 e tamanho mínimo de 100.

    -   Novamente, adapte o comando abaixo para a amostra que esta analisando, substituindo HG00099 pelo código dela:

        ```{bash,eval=FALSE}
        java -jar '/home/USER/Downloads/Trimmomatic-0.39/trimmomatic-0.39.jar' PE -phred33 ShortReadsFastq/HG00099_r1.fastq ShortReadsFastq/HG00099_r2.fastq trimmed_r1.fastq trimmed_r1_unpaired.fastq trimmed_r2.fastq trimmed_r2_unpaired.fastq ILLUMINACLIP:'/home/USER/Downloads/Trimmomatic-0.39/adapters/TruSeq3-PE.fa':2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:27 MINLEN:100
        ```
4.  **Filtragem de Leituras Curtas ou Longas:**
    -   Dependendo do seu experimento, você pode querer filtrar leituras muito curtas ou muito longas que possam representar artefatos ou problemas experimentais.

<!-- 5. **Avaliação de Conteúdo Específico:** -->

<!--    - Se o seu experimento envolver amplo enriquecimento de regiões específicas (por exemplo, ChIP-seq), verifique a qualidade nessas regiões específicas para garantir que as leituras estejam enriquecidas onde você espera. -->

5.  **Avaliação de Qualidade Pós-Trimagem:**
    -   Após a trimagem e filtragem, execute novamente o `FASTQC` para avaliar como essas etapas afetaram a qualidade dos dados. Isso ajudará a garantir que você atingiu os padrões de qualidade desejados.

<!-- 6. **Estimativa de Diversidade e Contaminação:** -->

<!--    - Em alguns casos, pode ser útil estimar a diversidade da amostra e verificar a presença de contaminação. Ferramentas como FastQ Screen podem ser úteis nesse contexto. -->

<!-- 6.  **Relatório Final de Controle de Qualidade:** -->

<!--     -   Compile todos os resultados de QC em um relatório final que destaque os principais aspectos da qualidade dos dados. Isso é útil para comunicação interna, bem como para garantir a transparência na publicação de resultados. -->

<!-- Essas etapas são fundamentais para garantir que os dados utilizados nas análises subsequentes sejam de alta qualidade e que os resultados sejam mais confiáveis. Lembre-se de que os detalhes específicos podem variar com base no tipo de experimento e na plataforma de sequenciamento utilizada. -->
